// File generated by FlutterFire CLI — do not edit manually.
// API keys are injected at build time via --dart-define.
// Local dev: flutter run --dart-define-from-file=.firebase.env
// CI: keys are stored as GitHub Actions secrets (FIREBASE_*_API_KEY).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
    appId: '1:770507992356:web:2bfd86e23dba0106dcd7b1',
    messagingSenderId: '770507992356',
    projectId: 'pahlevani-74ba6',
    authDomain: 'pahlevani-74ba6.firebaseapp.com',
    storageBucket: 'pahlevani-74ba6.firebasestorage.app',
    measurementId: 'G-S4083DQZ74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
    appId: '1:770507992356:android:0167ae603436d2b3dcd7b1',
    messagingSenderId: '770507992356',
    projectId: 'pahlevani-74ba6',
    storageBucket: 'pahlevani-74ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
    appId: '1:770507992356:ios:c3aa337e3a232b28dcd7b1',
    messagingSenderId: '770507992356',
    projectId: 'pahlevani-74ba6',
    storageBucket: 'pahlevani-74ba6.firebasestorage.app',
    iosBundleId: 'com.pahlevani.app',
  );
}
