import 'package:flutter/material.dart';
import 'package:pahlevani/domain/entities/playlist/playlist.dart';
import 'package:pahlevani/domain/entities/playlist/audio.dart';

class EditPlaylistPage extends StatefulWidget {
  final Playlist playlist;

  const EditPlaylistPage({
    super.key,
    required this.playlist,
  });

  @override
  State<EditPlaylistPage> createState() => _EditPlaylistPageState();
}

class _EditPlaylistPageState extends State<EditPlaylistPage> {
  late List<Audio> _songs;
  late TextEditingController _titleController;
  late TextEditingController _descriptionController;
  bool _hasChanges = false;

  @override
  void initState() {
    super.initState();
    _songs = List.from(widget.playlist.songs);
    _titleController = TextEditingController(text: widget.playlist.title);
    _descriptionController = TextEditingController(text: widget.playlist.description);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _removeSong(int index) {
    setState(() {
      _songs.removeAt(index);
      _hasChanges = true;
    });
  }

  void _reorderSongs(int oldIndex, int newIndex) {
    setState(() {
      if (oldIndex < newIndex) {
        newIndex -= 1;
      }
      final song = _songs.removeAt(oldIndex);
      _songs.insert(newIndex, song);
      _hasChanges = true;
    });
  }

  void _saveChanges() {
    if (!_hasChanges) {
      Navigator.pop(context);
      return;
    }

    final updatedPlaylist = Playlist(
      id: 0, // New ID will be generated by repository
      title: _titleController.text,
      description: _descriptionController.text,
      difficulty: widget.playlist.difficulty,
      createdAt: DateTime.now(),
      songs: _songs,
      isUserCreated: true, // Always mark as user-created
    );

    Navigator.pop(context, updatedPlaylist);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Edit ${widget.playlist.title}'),
        actions: [
          IconButton(
            icon: const Icon(Icons.save),
            onPressed: _saveChanges,
          ),
        ],
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              children: [
                TextField(
                  controller: _titleController,
                  decoration: const InputDecoration(
                    labelText: 'Playlist Title',
                    border: OutlineInputBorder(),
                  ),
                  onChanged: (value) => setState(() => _hasChanges = true),
                ),
                const SizedBox(height: 16),
                TextField(
                  controller: _descriptionController,
                  decoration: const InputDecoration(
                    labelText: 'Description',
                    border: OutlineInputBorder(),
                  ),
                  maxLines: 2,
                  onChanged: (value) => setState(() => _hasChanges = true),
                ),
              ],
            ),
          ),
          Expanded(
            child: ReorderableListView.builder(
              itemCount: _songs.length,
              onReorder: _reorderSongs,
              itemBuilder: (context, index) {
                final song = _songs[index];
                return ListTile(
                  key: ValueKey(song.id),
                  leading: const Icon(Icons.drag_handle),
                  title: Text(song.name),
                  subtitle: Text(song.author),
                  trailing: IconButton(
                    icon: const Icon(Icons.delete, color: Colors.red),
                    onPressed: () => _removeSong(index),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
} 